### ISSUE TITLE
"Current-ness" as Property

### ISSUE THREAD

**Issue by darth-cheney** [UnitedLexCorp/SimpleTalk#115]
## What ##
As it stands now, the "current-ness" of a Stack (in the World) or a Card (in a Stack) is determined solely by adding a class to the corresponding view's element. This is also how we navigate through Cards and Stacks.
  
We need to change this -- the current-ness should be a property on either the Card or the Stack in question, and the views/System should react to that property changing.
  
## Options ##
There are two ways to go, and it's unclear which is better.
  
In the first method, a Card changes its "current" boolean property to true. It would be a dynamic prop that then goes into its parent Stack and sets all other Cards "current" to false.
  
In the second method, the Stack itself keeps track of which of its Card subparts is the current one, as some property on itself. This is that changes and views react to that change.

**Comment by dkrasner** [comment]
I think it should be the latter:

"current-ness" is not a property of a card, it's an indication of which card is current _on the stack_, i.e. it's a property of the stack. We don't want the card to decided whether it is current, b/c it needs to do this in consort with all the other cards making sure they are not current or are no longer current. So I think making this a property of the stack `current-card: cardId`, which is dynamic, would be the best way to go. 

The stack could make sure that it only has one current card, and even check on condition to see if making a selected card current can be done at any given moment. (Imagine we have a remote, collaborative, setup and two people are working on the same current card, then one navigates to another - we might or might not allow such a navigation)
