### ISSUE TITLE
Copy and Paste Parts

### ISSUE THREAD

**Issue by darth-cheney** [UnitedLexCorp/SimpleTalk#135]
I could really have used a copy and paste functionality in the course of creating the layout examples stack. With the new serialization pattern it shouldn't be too bad to implement.

**Comment by dkrasner** [comment]
some of this worked in the drag&drop functionality (recall from the world catalogue, really anywhere, you could drag&drop and it would make a copy or a new part), but i think it needs reworking 

one thing to do decide is what a copy is: 
* a new model + view of the same type
* a copy of the model + view, i.e. a new model with all the same part props as the old one
* or a an additional view on the _same_ model

my personal feeling is that it should be the 2nd option, but maybe we need a way to choose between the first two or all three

**Comment by darth-cheney** [comment]
> a copy of the model + view, i.e. a new model with all the same part props as the old one
  
I think this is the right option, because it's the equivalent of a de-serialized version of the original part with a new id, which is exactly what we want. We could simply reuse a lot of that functionality.
  
The ability to copy should be right in the halo (in addition to being a clipboard manipulation, which we should also include). Might be time to start thinking about a custom context menu as well

**Comment by dkrasner** [comment]
yeah maybe all parts could get a "copy" & "paste" commands?

"copy" -> copy the serialization for (selected) object to clipboard
"paste"-> create a new model from the serialization and add it to (selected) object

this way you could script `tell button "My Button" of current card to copy \n tell first window of current card to paste"?

just have to think through this and general clipboard interaction
