### ISSUE TITLE
Update `add` command implementation for implicit this part

### ISSUE THREAD

**Issue by darth-cheney** [UnitedLexCorp/SimpleTalk#139]
Right now the grammatical/semantic implementation of the primitive `add/to` command requires that we supply an explicit ObjectSpecifier. We should change this so that leaving off the ObjectSpecifier means, implicitly, to attempt to add the part to the current context part (the one whose script is executing).
  
This came up from @dkrasner 's example here:
https://github.com/UnitedLexCorp/SimpleTalk/pull/133#issuecomment-797729984

**Comment by dkrasner** [comment]
this looks resolved to me @darth-cheney 

i tried some of the examples which were failing earlier, but they no longer are. Perhaps the various merges and conflict resolution took care of it   closing
