### ISSUE TITLE
Navigator gets stuck crashing the system

### ISSUE THREAD

**Issue by dkrasner** [UnitedLexCorp/SimpleTalk#179]
hard to reproduce deterministically but this is quite common:

![image](https://user-images.githubusercontent.com/1154326/114387279-85f6b300-9b92-11eb-8503-a1c481b4f290.png)

sometimes it just doesn't open at all 

sometimes it opens but no stacks or cards appear:
![image](https://user-images.githubusercontent.com/1154326/114399127-dffe7500-9ba0-11eb-9751-6e27a569f950.png)

or it appears doubling up
![image](https://user-images.githubusercontent.com/1154326/114399244-fd334380-9ba0-11eb-9953-224785474db3.png)

**Comment by darth-cheney** [comment]
Closed by #183
