### ISSUE TITLE
Navigator and layouts don't play nice

### ISSUE THREAD

**Issue by dkrasner** [UnitedLexCorp/SimpleTalk#180]
Navigator can start to push the world/stack/card layout up off-screen like so

![image](https://user-images.githubusercontent.com/1154326/114387386-a9216280-9b92-11eb-8780-4cac40c5ecc1.png)

these can be cumulative. example opening subsequent script editors can push the navigator up

This effectively kills the system since there is no way to access parts pinned at the top

**Comment by darth-cheney** [comment]
Closed by #183
