### ISSUE TITLE
Rethink (and potentially separate) current-{stack|card} behavior from visibility

### ISSUE THREAD

**Issue by mdeland** [UnitedLexCorp/SimpleTalk#40]
In the work on [implementing go-to functionality](https://github.com/UnitedLexCorp/SimpleTalk/pull/35) we learned that it is currently tricky to allow arbitrary navigation via `go to` (e.g. `go to card X`). This is in part because the classes `current-stack` and `current-card` are being used to keep track of "focus" state and control what's visible on the screen, but there's no framework (yet) for models controlling which of their children are visible.

Take the following schematic example
```
<world>
  <stack 1 current-stack>
    <card 2 current-card />
  </stack 1>
  <window 3>
    <stack 4>
      <card 5 current-card />
    </stack 4>
  </window 3>
</world>
```

In the current framework, cards 2 and 5 are intended to be visible on the screen.  If the message is passed to `go to card 5`... should `stack 1` remain visible?  If the message is then passed to return `go to card 2`, should `card 5` still be visible?  

There's no framework for models to control the visibility of their children when these messages are executed, so in the referenced PR we punted that decision and restricted the scope of `go to` to only apply to direct children parts, but this should be re-designed to allow greater functionality.

**Comment by darth-cheney** [comment]
With the new serialization changes, this issue has been updated as #115. Closing.
