### ISSUE TITLE
Generalize systemObject grammar node

### ISSUE THREAD

**Issue by dkrasner** [UnitedLexCorp/SimpleTalk#44]
The current implementation of `systemObject` in our grammar is as follows:

```
systemObject (system object such as card, stack etc)
	= ("b"| "B") "ackground" | ("b" | "B") "utton" | ("c" | "C") "ard" | ("f" | "F") "ield" | ("s" | "S") "tack"
```

This is fine if we stick to only core objects (parts), but will become an issue if we allow people to create new parts and reference those. 

It would be good to relax this condition and allow for more general references to objects/part. What those references are (could be as lax as a string of alphanumeric characters or something more restricted), is to be determined here. 

Minor changes would have to be made for grammar, compiler and object/part related tests.

**Comment by darth-cheney** [comment]
We have decided to being with a strict collection of primitive parts, and these will be directly written into the grammar. Closing.
