### ISSUE TITLE
Nested Halo Activation

### ISSUE THREAD

**Issue by darth-cheney** [UnitedLexCorp/SimpleTalk#78]
## What ##
In order to prevent mass confusion when activating many halos, we should explore the possibility of implementing Squeak-like halo activation patterns.
  
This means that Parts that are in the same subtree should not both have their halos open. If we open a halo on a child, we should not also be able to open it on the parent -- one or the other should be toggled off first.
  
Additionally, we will want to implement the "multiple halo click" that ascends the hierarchy opening halos on the parent part with each immediate subsequent halo click on an already opened halo.

**Comment by dkrasner** [comment]
taken care of in #151
